
name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
 zap_dast:
   runs-on: ubuntu-latest
   steps:
     - name: ZAP Scan
       uses: zaproxy/action-full-scan@v0.9.0
       with:
         docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
         target: 'http://testhtml5.vulnweb.com/'
        # Optional command options could be uncommented and used here
        # cmd_options: '-a'
        
        # Optional HTTP login configuration could be uncommented and used here
        # http_login_form: '/app/login'
        # http_login_http_username: 'testuser'
        # http_login_http_password: ${{ secrets.ZAP_USER_PW }}
        
 acunetix_dast:
   runs-on: ubuntu-latest
   steps:
     - name: Trigger Acunetix Scan
       run: |
         curl -k -i --request POST \
           --url "https://online.acunetix.com/api/v1/scans" \
           --header "X-Auth: 1986ad8c0a5b3df4d7028d5f3c06e936c9f1fb4e583a34a3ab293b65715cf6429" \
           --header "content-type: application/json" \
           --data '{"profile_id":"11111111-1111-1111-1111-111111111111", "schedule":{"disable":false,"start_date":null,"time_sensitive":false}, "user_authorized_to_scan":"yes", "target_id":"09590b51-f76c-489a-81e7-8d06abad876d"}'

 burp_dast:
   runs-on: ubuntu-latest
   steps:
     - name: Run Dastardly Action Step
       continue-on-error: true
       uses: PortSwigger/dastardly-github-action@main
       with:
         target-url: 'http://testhtml5.vulnweb.com/'
